# Generated by Django 5.0.7 on 2024-08-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_unit_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='quiz.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_unit', to='quiz.category'),
            preserve_default=False,
        ),
    ]
