# Generated by Django 5.0.7 on 2024-08-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quiz', '0008_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_categories', to='core.maincategory'),
            preserve_default=False,
        ),
    ]
