# Generated by Django 5.0.7 on 2024-08-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0002_remove_restoreanswer_answer_restoreanswer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorecategory',
            name='name',
        ),
    ]
