# Generated by Django 5.0.7 on 2024-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0004_restorecategory_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restore',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restoreanswer',
            name='num',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
