# Generated by Django 5.0.7 on 2024-08-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_remove_problem_num_problemanswer_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemanswer',
            name='num',
        ),
        migrations.AddField(
            model_name='problem',
            name='num',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
