# Generated by Django 5.0.7 on 2024-08-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_remove_problemanswer_num_problem_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcategory',
            name='name',
        ),
    ]
