# Generated by Django 5.0.7 on 2024-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_problemcategory_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemanswer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
