# Generated by Django 5.0.7 on 2024-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_alter_problemanswer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(),
        ),
    ]
