# Generated by Django 5.0.7 on 2024-09-02 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maincategory_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='managers',
        ),
    ]
