# Generated by Django 5.0.7 on 2024-09-02 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_remove_maincategory_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(related_name='managed_categories', to='core.maincategory')),
                ('user', models.ManyToManyField(related_name='managed_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
