# Generated by Django 5.0.7 on 2024-09-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_manager',
        ),
    ]
